### ISSUE TITLE
Will this affect 1.7.10 forge servers?

### ISSUE THREAD

**Issue by Time6628** [SilverCory/SpongePls#5]
I run a 1.7.10 modded network, and I was planning to begin adding 1.10.2 packs to my network. 
I got all the bungeecord stuff setup, but when I went to test the 1.10.2 pack All The Mods through bungee, this happened:
![alt-text](http://image.prntscr.com/image/930e72c29a3540ef9f232451e601631b.png)

So I did some googling, and found this plugin. My only concern is that this will affect the 1.7.10 part of my network. Do you have any idea if it will?

**Comment by SilverCory** [comment]
Try it and tell me!

Honestly, this forge header has caused tonnes of issues, not just within Bungeecord but other things, IMO they need to redo the system a bit. I'm not too up to date with everything forge and modding, and I only made this because someone said it was impossible to implement into a plugin.
